# Generated by Django 3.0 on 2026-01-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='letting',
                    name='address',
                ),
                migrations.DeleteModel(
                    name='Letting',
                ),
                migrations.DeleteModel(
                    name='Address'
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Letting',
                    table='lettings_letting',
                    ),
                migrations.AlterModelTable(
                    name='Address',
                    table='lettings_address'
                )
            ],
        )
    ]
